### PR TITLE
Added better intro to Symfony

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by cafferata** [comment]
@cmodijk This pull request looks fine by me. If you agree would you like to merge this?

**Comment by Nyholm** [comment]
I will make some more PRs after this is merged. Just did not want to make one gigantic one.

**Comment by Nyholm** [comment]
Can I merge this?

**Comment by Nyholm** [comment]
Ping @cmodijk

**Comment by Nyholm** [comment]
Ping?

**Comment by cmodijk** [comment]
@Nyholm Tnx i just merged it.

**Comment by Nyholm** [comment]
Awesome. Thanks!

**Comment by cmodijk** [comment]
@Nyholm Feel free to improve the docs and merge these things your self.

**Pull request merged**
