### PR TITLE
Added logo

### PR DESCRIPTION
**Pull request by Nyholm**
This org looked so empty without a logo. I just created a simple text logo =)

### CODE REVIEW

**Comment by cmodijk** [comment]
@Nyholm I don't think we should advertise SimpleBus as a Event Sourcing library it's a message bus for commands and events but it does also not support the Q in CQRS. What are your thoughts on this?

**Comment by Nyholm** [comment]
Maybe you are correct. I just threw in as many buzz words I could. I'll update this pr

**Comment by Nyholm** [comment]
How about this?

**Comment by cmodijk** [comment]
Tnx @Nyholm looks good to me

**Comment by Nyholm** [comment]
Thank you for merging!

**Pull request merged**
