### PR TITLE
Explain Autowiring

### PR DESCRIPTION
**Pull request by ruudk**
https://github.com/SimpleBus/AsynchronousBundle/pull/15
https://github.com/SimpleBus/SymfonyBridge/pull/52

### CODE REVIEW

**Comment by kbond** [comment]
Am I missing something here? I had to add the following aliases to my config for this to work:

```yaml
services:
    SimpleBus\SymfonyBridge\Bus\CommandBus: '@command_bus'
    SimpleBus\SymfonyBridge\Bus\EventBus: '@event_bus'
```

**Comment by cmodijk** [comment]
@ruudk Do you know why @kbond needs to at these service aliases?

**Comment by ruudk** [comment]
Hmm, is the Symfony Bridge enabled in the kernel?

**Comment by kbond** [comment]
Yes, from what I can see, https://github.com/SimpleBus/SymfonyBridge/pull/52 doesn't actually enable these classes to be autowired. These aliases still need to be added. Does it work for you?

**Comment by ruudk** [comment]
'command_bus' is simple an alias of 'simplebus.command_bus'. So it should just work.

What version of symfony are you using?

What happens when you do 
```php
$this->get(CommandBus::class)
```

**Comment by kbond** [comment]
I am using 3.4@RC2. That gives me the following error:

```
...references class "SimpleBus\SymfonyBridge\Bus\CommandBus" but no such service exists. You should maybe alias this class to the existing "simple_bus.command_bus" service.
```

I'm not sure how it is working for you.

**Comment by ruudk** [comment]
@kbond You are right. I'm sorry, I totally missed this. I will fix this the proper way in SymfonyBridge :v: /cc @cmodijk

**Pull request merged**
